.PHONY: install
install:
	poetry install --with dev,test
	make db
	npm install --no-audit --no-fund

.PHONY: test
test:
	poetry run pytest -x [[app_name]] tests

.PHONY: lint
lint:
	poetry run flake8 [[app_name]] tests

.PHONY: db
db:
	rm db/[[ app_name ]].sqlite || true
	proper db create_all
	proper db stamp
