[tool.poetry]
name = "proper"
version = "1.0"
description = "A web framework optimized for programmer happiness"
authors = ["Juan-Pablo Scaletti <juanpablo@jpscaletti.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/jpsca/proper"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers"
]
include = ["blueprints", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = "^3.6"
gevent = "^20.6"
hecto = "^1.200708"
itsdangerous = "^1.1"
jinja2 = "^2.11"
multipart = "^0.2"
passlib = "^1.7"
pyceo = "^2.200716"
properconf = "^1.200719"

[tool.poetry.dev-dependencies]
flake8 = "^3.8"
ipdb = "^0.13"
# mkdocs = "^1.1"
pygments = "^2.6"
pygments-github-lexers = "*"
pymdown-extensions = "^7.1"
pytest = "^5.4"
pytest-cov = "^2.10"
pytest-flake8 = "^1.0"
webtest = "^2.0"

[tool.poetry.scripts]
proper = "proper.cli:manager_run"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/jpsca/proper/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
