[metadata]
name = proper
version= 1.0
url = https://github.com/jpsca/proper
project_urls =
    Issue tracker = https://github.com/jpsca/proper/issues
author = Juan-Pablo Scaletti
author_email = juanpablo@jpscaletti.com
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Topic :: Internet :: WWW/HTTP :: WSGI
    Topic :: Software Development :: Libraries :: Application Frameworks
    License :: OSI Approved :: Apache Software License
license = Apache License Version 2.0
license_file = LICENSE
description = A web framework optimized for programmer happiness.
long_description = file:README.md
long_description_content_type = text/markdown
keywords =

[options]
packages = find:
include_package_data = true
python_requires = >=3.6,<4.0
install_requires =
    eventlet >= 0.26.1
    hecto >= 1.200708
    itsdangerous >= 1.1
    jinja2 >= 2.11
    kombu >= 5.0
    multipart >= 0.2
    passlib >= 1.7
    properconf >= 1.200809
    pyceo >= 2.200716
    python_socketio >= 4.6

[options.packages.find]
exclude =
    tests

[options.extras_require]
test =
    pytest
    pytest-cov
    WebTest

dev =
    black
    flake8
    mkdocs
    pygments
    pygments-github-lexers
    pymdown-extensions
    pytest
    pytest-cov
    tox
    WebTest

[options.entry_points]
console_scripts =
    proper = proper.cli:manager_run

[flake8]
select =
  B,  # bugbear
  B9,  # bugbear opinionated
  C,  # mccabe, comprehensions, commas
  E,  # pycodestyle errors
  F,  # pyflakes
  G,  # logging format
  I,  # imports
  P,
  Q,  # quotes
  RST,  # rst docstring formatting
  T0,  # print
  T4,  # mypy
  W,  # pycodestyle warnings

ignore =
    W503,  # W503 line break before binary operator
    E203,  # E203 whitespace before ':'

max-complexity = 10
max-line-length = 88

statistics = true
doctests = True
accept-encodings = utf-8

[tool:pytest]
addopts = --doctest-modules
