[tox]
skipsdist = True
envlist = py39,py38,py37,py36

[testenv]
skip_install = true
commands =
    pip install -U pip .[test]
    pytest -x proper tests

[coverage:run]
branch = True

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise NotImplementedError
    if __name__ == .__main__.:
    if 0:
omit =
	proper/base_channel.py
    proper/cli.py
    proper/server.py

[coverage:html]
directory = covreport
