import pyceo
import properconf

from proper import generators, static


ENCRIPTED_HEADER = """# -------------------------------------------------------------
# -- DO NOT EDIT THIS FILE --
# Use `bin/manage secrets %s`
# -------------------------------------------------------------
#
"""

class Cli:
    def __init__(self, app):
        self.app = app

    @property
    def ApplicationCli(self):

        class ApplicationCli(pyceo.Cli):
            """Application-specific commands.

            You don't need a special console to interact with the app,
            just run `ipython` or the regular python interpreter and import
            the application, like a regular python package.

            """

            _app = self.app

            def secrets(self, env):
                """Edit your encrypted secrets.

                Arguments:

                - env:
                    Name of the environment (e.g.: "development", "production", etc.)
                    It will be used for finding the encrypted file (e.g.: "development.enc.toml")
                    and the key (e.g.: "development.key").

                """
                path = self._app.root_path / "config"
                header = ENCRIPTED_HEADER % (env, )
                properconf.edit_secrets(path, env, secrets_header=header)

            g = self.GeneratorsCli
            static = self.StaticCli

        return ApplicationCli

    @property
    def GeneratorsCli(self):
        attrs = {
            "__doc__": """Generate new code.""",
            "_app": self.app,
        }

        for name in ("resource", "controller", "model"):
            func = getattr(generators, name)

            def cmd(self, *args, **kwargs):
                return func(self._app, *args, **kwargs)

            cmd.__name__ = name
            cmd.__doc__ = func.__doc__
            attrs[name] = cmd

        return type("GeneratorsCli", (pyceo.Cli, ), attrs)

    @property
    def StaticCli(self):
        attrs = {
            "__doc__": """Manage static files.""",
            "_app": self.app,
        }

        for name in ("bundle", "build", "clean", "compile"):
            func = getattr(static, name)

            def cmd(self, *args, **kwargs):
                return func(self._app, *args, **kwargs)

            cmd.__name__ = name
            cmd.__doc__ = func.__doc__
            attrs[name] = cmd

        return type("StaticCli", (pyceo.Cli, ), attrs)
