"""
Makes a unique request id available to the `req.request_id` variable
and sends the same id to the client via the "X-Request-Id" header.

This unique request id can be used to trace a request end-to-end and would typically
end up being part of log files from multiple pieces of the stack.

The unique request id is either based on the "X-Request-Id" header in the request,
which would typically be generated by a firewall, load balancer, or the web server,
or, if this header is not available, a random uuid. If the header is accepted from
the outside world, we sanitize it to a max of 200 chars and alphanumeric and
dashes only.
"""
import re
from uuid import uuid4


__all__ = ("set_request_id",)

REQUEST_ID_HEADER = "X-Request-Id"
REQUEST_ID_MAX_LENGTH = 200
RE_NON_ASCII = re.compile(r"[^\x00-\x7f-]")


def set_request_id(req, resp, app):
    request_id = req.headers.get(REQUEST_ID_HEADER)
    if request_id:
        request_id = sanitize_request_id(request_id)
    else:
        request_id = new_request_id()

    req.request_id = request_id
    resp.set_header(REQUEST_ID_HEADER, request_id)


def sanitize_request_id(request_id: str) -> str:
    return RE_NON_ASCII.sub("", request_id[:REQUEST_ID_MAX_LENGTH])


def new_request_id() -> str:
    return str(uuid4())
