"""Helper for sweeping abandoned rich-text uploads.

When the editor pre-uploads a file (e.g. a user drops an image into the
rich text editor), an `Attachment` row is created with `source="direct"`
and `pending=True`. The flag flips to `False` once a parent record's
save confirms that the attachment is referenced from a body. If the
user closes the tab without submitting, the row stays pending forever.

This module exposes a pure function that finds such orphans and
schedules them for purge. The user's app wraps the call in a Huey
periodic task in their `tasks/` folder (generated by the rich_text
blueprint installer), which is where the cron schedule and the grace
period live - making them tunable without touching framework code.
"""
import typing as t
from datetime import timedelta

import peewee as pw


if t.TYPE_CHECKING:
    from ..storage import _Attachment


def purge_abandoned_uploads(
    attachment_cls: "type[_Attachment]",
    *,
    grace_hours: int = 24,
    source: str = "direct",
) -> int:
    """Schedule purges for rich-text uploads still pending past the grace
    period. Returns the count of rows scheduled for purge.

    Arguments:
        attachment_cls:
            The user's `Attachment` model class.
            It has `source`, `pending`, `created_at` columns (added by the storage addon)
            and a `purge_later()` instance method.
        grace_hours:
            How long an unconfirmed upload may live before it counts as
            abandoned. Defaults to 24h.
        source:
            The source type of the attachment. Defaults to "direct".
    """
    cutoff = pw.utcnow() - timedelta(hours=grace_hours)  # type: ignore
    cls = attachment_cls
    rows = cls.select().where(
        (cls.source == source)
        & (cls.pending == True)  # noqa: E712
        & (cls.created_at < cutoff)
    )
    count = 0
    for att in rows:
        att.purge_later()
        count += 1
    return count
