.PHONY: install
install:
	uv sync --group dev --group test

.PHONY: test
test:
	uv run pytest -x [[ app_name ]] tests

.PHONY: lint
lint:
	uv run ruff check .

.PHONY: lint-fix
lint-fix:
	uv run ruff check . --fix