.PHONY: dbuild
dbuild:
	docker compose build --build-arg UID=$$(id -u) --build-arg GID=$$(id -g) --build-arg USER=$$(whoami)

.PHONY: dup
drun:
	docker compose up -d

.PHONY: ddown
ddown:
	docker compose down

.PHONY: dshell
dshell:
	docker compose exec dev bash

.PHONY: install
install:
	uv sync --group dev --group test

.PHONY: test
test:
	uv run pytest -x [[ app_name ]] tests

.PHONY: lint
lint:
	uv run ruff check .

.PHONY: lint-fix
lint-fix:
	uv run ruff check . --fix