import copy
import queue
import re
from pathlib import Path
from typing import Any, Dict, Optional

import texteditor
import yaml
from cryptography.fernet import Fernet
from proper_cli import confirm
try:
    from yaml import CLoader as YamlLoader, CDumper as YamlDumper
except ImportError:  # pragma: no cover
    from yaml import YamlLoader, YamlDumper


Queue = getattr(queue, "SimpleQueue", queue.Queue)

ENCRYPTED_FILE = "%s.enc.yaml"
KEY_FILE = "%s.key"
MASTER_KEY_FILE = "master.key"
RX_COMMENT = re.compile(rb"\s*#[^\n]*\n")
INTRO_MSG = "You can edit your secrets now. Don't forget to save your changes"
ENCRIPTED_HEADER = """# -------------------------------------------------------------
# -- DO NOT EDIT THIS FILE --
# Use `proper credentials %s`
# -------------------------------------------------------------
#
"""
DEFAULT_SECRETS = """# -------------------------------------------------------------------
# This is an encrypted config file in YAML language
# (https://en.wikipedia.org/wiki/YAML)
#
# Your can safely store here credentials like API keys and such,
# and commit this file to your source version control system.
# -------------------------------------------------------------------

# name: "value"
"""
HIDDEN_VALUE = "..."


class Cryptex:
    def __init__(self, path: Path, env: str) -> None:
        self.path = path
        self.env = env
        self.enc_path = path / (ENCRYPTED_FILE % (env, ))
        self.key_file = KEY_FILE % (self.env,)
        self.key_path = path / self.key_file

    def load(self) -> Dict[str, Any]:
        if not self.enc_path.exists():
            return {}
        key = self.read_key()
        content = self.read(key)
        config = self.load_yaml(content)
        return config or {}

    def edit(self) -> None:
        """Edit your encrypted credentials in the default text editor."""
        key = self.read_key()
        if self.enc_path.exists():
            content = self.read(key) or DEFAULT_SECRETS
        else:
            if not confirm(f"{self.enc_path} does not exists. Create?", default=False):
                return
            if not key:
                key = self.new_key_file()
            content = DEFAULT_SECRETS

        print(INTRO_MSG)
        new_content = texteditor.open(content, extension=self.enc_path.suffix)
        self.save(key, new_content)

    def read_key(self) -> None:
        self.key = None
        key_path = self.key_path
        if not key_path.is_file():
            key_path = self.path / MASTER_KEY_FILE
            if not key_path.is_file():
                return
        self.key = key_path.read_bytes().strip()

    def read(self, key: bytes) -> str:
        if not key:
            raise IOError(
                f"Key not found. Either put a `{self.key_file}` or"
                f" a `{MASTER_KEY_FILE}` beside your encrypted credentials."
            )
        return self.decrypt(key)

    def decrypt(self, key: bytes) -> str:
        enc_content = RX_COMMENT.sub(b"", self.enc_path.read_bytes()).strip()
        if not enc_content:
            return ""
        content = Fernet(key).decrypt(enc_content)
        return content.decode("utf8")

    def save(self, key: bytes, content: str) -> None:
        enc_content = Fernet(key).encrypt(content.encode("utf8"))
        header = ENCRIPTED_HEADER % (self.env, )
        self.enc_path.write_bytes(header.encode("utf8"))
        summary = self.get_summary(content)
        with self.enc_path.open("ab") as f:
            f.write(summary.encode("utf8"))
            f.write(b"\n#\n")
            f.write(enc_content)

    def get_summary(self, content: str) -> str:
        config = self.load_yaml(content)
        if not config:
            return ""
        config = self.hide_values(config)
        text = yaml.dump(config, Dumper=YamlDumper).strip()
        return "#  " + "\n#  ".join(text.split("\n"))

    def load_yaml(self, content: str) -> Optional[Dict[str, Any]]:
        try:
            return yaml.load(content, Loader=YamlLoader) or {}
        except (TypeError, ValueError):
            print(
                "-- WARNING: The encrypted config has syntax errors and"
                " is not a valid YAML file."
            )
            return

    def hide_values(self, config: Dict[str, Any], maxdepth: int = 2) -> Dict[str, Any]:
        """Takes a dict and return another with all the non-dict values
        or those deeper than `maxdepth` replaced by `empty`.
        """
        dicts = Queue()
        hconfig = copy.deepcopy(config)
        dicts.put((0, hconfig))

        while dicts.qsize() > 0:
            level, subdict = dicts.get()
            for key, value in subdict.items():
                if level < maxdepth and isinstance(value, dict):
                    dicts.put((level + 1, value))
                    continue
                subdict[key] = HIDDEN_VALUE

        return hconfig

    def new_key_file(self) -> bytes:
        key = Fernet.generate_key()
        self.key_path.write_bytes(key)
        return key
