services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        proper db create_tables
        proper run
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
      - redis
    ports:
      - "2300:2300"
    volumes:
      - .:/app/
  static:
    build:
      context: .
      dockerfile: Dockerfile
    command: tailwindcss -i /app/static_src/css/app.css -o /app/static/css/app.css
    volumes:
      - .:/app/
