.PHONY: install
install:
	poetry install --with dev,test
	tailwindcss_install
	pip install -e ../proper
	proper db migrate

.PHONY: test
test:
	pytest -x [[ app_name ]] tests

.PHONY: lint
lint:
	ruff check .
