.PHONY: lock
lock:
	uv pip compile --all-extras pyproject.toml -o requirements-dev.txt
	uv pip compile --extra=test pyproject.toml -o requirements-test.txt
	uv pip compile pyproject.toml -o requirements.txt

.PHONY: install
install:
	make lock
	uv pip install -r requirements-dev.txt
	tailwindcss_install
	uv pip install -e ../proper
	proper db migrate

.PHONY: test
test:
	pytest -x [[ app_name ]] tests

.PHONY: lint
lint:
	ruff check .
