[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "[[ app_name ]]"
version = "1.0"
description = ""
authors = ["Lorem Ipsum <lorem.ipsum@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.dev0"
fodantic = "*"
gunicorn = "^23.0.0"
proper = { path = "../proper/", develop = true }
# psycopg2-binary = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = ">=0.2.0"
# pytailwindcss = ">=0.2.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = ">=7.2.0"


[tool.pytest.ini_options]
addopts = "--doctest-modules"


[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py312"

exclude = [".*"]
include = ["*.py"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
fixable = ["ALL"]

ignore = [
  # x is too complex
  "C901",
  # whitespace before ':'
  "E203",
  "E501",
  # x defined from star imports
  "F405",
  # line break before binary operator
  "W505",
  "W605",
]
select = [
  # bugbear
  "B",
  # mccabe"", comprehensions, commas
  "C",
  # pycodestyle errors
  "E",
  # pyflakes
  "F",
  # logging format
  "G",
  # imports
  "I",
  # quotes
  "Q",
  # pycodestyle warnings
  "W",
]

[tool.ruff.lint.isort]
known-local-folder = ["[[ app_name ]]"]
known-third-party = []
no-lines-before = ["local-folder"]
relative-imports-order = "furthest-to-closest"
# Use two line after imports.
lines-after-imports = 2
