[uwsgi]
strict = true
master = true
; Shutdown when receiving SIGTERM (default is respawn)
die-on-term = true
enable-threads = true
need-app = true
single-interpreter = true
vacuum = true
close-on-exec = true

;log-drain = .*/static/.*  : in linux requires libpcre-dev
log-format =  %(status) %(method) %(uri) | %(rsize)B in %(msecs)ms

http = :2300
processes = 1
workers = 1

wsgi-file = wsgi.py
callable = app
honour-stdin = true
python-autoreload = 1
if-env = VIRTUAL_ENV
virtualenv = %(_)
endif =

hook-post-app = exec:proper _show_welcome --port 2300
