# HTTP methods (minus CONNECT and TRACE)
GET = "GET"
HEAD = "HEAD"
POST = "POST"
PUT = "PUT"
DELETE = "DELETE"
OPTIONS = "OPTIONS"
PATCH = "PATCH"
RESTORE = "RESTORE"

FLASHES_SESSION_KEY = "_flashes"
