.PHONY: help
help:
	@echo "clean - remove build/python artifacts"
	@echo "test - run tests"
	@echo "lint - check style with flake8"
	@echo "install - install for development"
	@echo "dbsetup - reset the database"
	@echo "run - run the development server"
	@echo "deploy - install in production"

.PHONY: clean
clean: clean-build clean-pyc

.PHONY: clean-build
clean-build:
	rm -rf build/
	rm -rf dist/
	rm -rf *.egg-info
	rm -rf pip-wheel-metadata

.PHONY: clean-pyc
clean-pyc:
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '.pytest_cache' -exec rm -rf {} +

.PHONY: test
test:
	python -m pytest -x [[ name ]]/tests

.PHONY: lint
lint:
	python -m flake8 --config=setup.cfg [[ name ]]

.PHONY: reqs
reqs:
	cd requirements && CUSTOM_COMPILE_COMMAND="make reqs" pip-compile -v requirements.in
	cd requirements && CUSTOM_COMPILE_COMMAND="make reqs" pip-compile -v development.in
	cd requirements && CUSTOM_COMPILE_COMMAND="make reqs" pip-compile -v production.in

.PHONY: install
install:
	pip install -U pip wheel
	pip install -r requirements/requirements.txt
	pip install -r requirements/development.txt
	pip install -e .
	cd static && npm install

.PHONY: dbsetup
dbsetup:
	dropdb [[ name ]] || true
	dropdb [[ name ]]_tests || true
	createdb [[ name ]] || true
	createdb [[ name ]]_tests || true
	alembic upgrade head

.PHONY: migration
migration:
	alembic revision --autogenerate
