.PHONY: setup
setup:  # Requires an active virtualenv
	pip install -U pip wheel --quiet
	pip install -r requirements/dev-requirements.txt
	pip install -e .
	make db
	npm install --no-audit --no-fund

.PHONY: test
test:
	pytest -x tests

.PHONY: lint
lint:
	flake8 --config=setup.cfg [[ app_name ]]

.PHONY: db
db:
	rm db/[[ app_name ]].sqlite || true
	proper db create_all
	proper db stamp
