[uwsgi]
strict = true
master = true
; Shutdown when receiving SIGTERM (default is respawn)
die-on-term = true
enable-threads = true
need-app = true
single-interpreter = true
vacuum = true

;log-drain = .*/static/.*  : in linux requires libpcre-dev
log-format =  %(status) %(method) %(uri) | %(rsize) bytes in %(msecs) ms

http = :2300
hook-post-app = exec:proper welcome --port 2300
processes = 1
workers = 1

wsgi-file = wsgi.py
callable = app
honour-stdin = true
python-autoreload = 1
if-env = VIRTUAL_ENV
virtualenv = %(_)
endif =
