# -------------------------------------------------------------
# Testing config
# -------------------------------------------------------------

debug = false
secret_key = "---- This is a fake secret key just for testing ----"
