---
nav:
  - index.md

site_name: Proper
site_description: A web framework optimized for programmer happiness.
site_author: Juan-Pablo Scaletti
site_url: https://properframework.dev

repo_name: GitHub
repo_url: https://github.com/jpscaletti/proper

extra_css:
  - css/monokai.css
  - css/extra.css

# Customization
extra:
  social:
    - type: globe
      link: https://properframework.dev
    - type: github-alt
      link: https://github.com/jpscaletti/proper

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
      guess_lang: false
  - smarty
  - toc:
      permalink: "#"
  - markdown.extensions.tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
